# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: bguyot <bguyot@student.42mulhouse.fr>      +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/11/30 10:55:44 by bguyot            #+#    #+#              #
#    Updated: 2021/11/30 10:55:46 by bguyot           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

SRC = ft_cat.c
LIB = -L. -lft

all:
	gcc -Wall -Wextra -Werror $(SRC) $(LIB) -o ft_cat

clean:

fclean: clean
	rm -f ft_cat
