# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: bguyot <bguyot@student.42mulhouse.fr>      +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/11/30 10:56:40 by bguyot            #+#    #+#              #
#    Updated: 2021/12/01 15:06:32 by bguyot           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

SRC = ft_tail.c

LIB = -L. -lft

all:
	gcc -Wall -Wextra -Werror $(SRC) $(LIB) -o ft_tail

clean:

fclean: clean
	rm -f ft_tail
